ec-nagano/ec_nagano_cake

app/controllers/shipping_addresses_controller.rb, app/views/shipping_addresses/edit.html.erb, app/views/shipping_addresses/index.html.erb
shipping_addressのコントローラーとviewの編集
=> #5 shipping_addressのコントローラーとviewの編集

app/models/category.rb, db/migrate/20200224124754_add_is_active_to_customer.rb, db/schema.rb
=> #21 customer モデルに is_active カラムを追加, categoryモデル を修正

app/controllers/admin/customers_controller.rb, app/controllers/admin/products_controller.rb, app/models/category.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb
issueに書いてある箇所以外に変更を加えました。
変更箇所
adminのcustomersコントローラ
adminn/customersのview(showとedit)
=> #19 edit customers_controller and show.html.rb and create edit.html.rb

app/controllers/customers/registrations_controller.rb, app/controllers/products_controller.rb, app/views/customers/show.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb
=> #36 customerのcustomerとproductの修正

app/views/products/show.html.erb
customer/product　showページの編集をしました。
=> #30　 customer/product　showページの編集をしました。

app/controllers/admin/products_controller.rb, app/views/admin/products/edit.html.erb
admin/products のコントローラ（edit,updateアクション）とedit ページを作成しました。
=> Create admin/products_controller and edit.html.erb

app/controllers/admin/categories_controller.rb, app/views/admin/customers/index.html.erb
admin/categories_controllerとadmin/customers/index.html.erbを修正。
（admin/categories_controller 　→　該当箇所にprivateの記述を追加）
（admin/customers/index.html.erb　→　会員ステータスを表示させるコードを修正）
=> #54 Edit admin/categories_controller and admin/customers/index.html.erb

app/controllers/orders_controller.rb, app/views/cart_items/index.html.erb, app/views/orders/confirm.html.erb
税込み金額の計算方法変更に伴う修正とorder のストロングパラメーターに関する修正。
=> #58 cart_item, order のコントローラーとビューを修正

app/controllers/admin/orders_controller.rb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb
間違えてcontrollerだけでなくshowとindexも書いてしまいました。
ごめんなさい。
よろしくお願いします。
=> #11 admin/order controllerの作成

app/controllers/admin/orders_controller.rb, app/views/admin/orders/show.html.erb
admin/order　showのproduct変数のところ修正しました。
またcontrollerの方は2重で更新することは避けることができたのですが
case whenをうまく扱えませんでした。
メンターさんに聞くか、教授に教えて欲しいです
=> #66 admin/controllerの修正

app/views/admin/products/index.html.erb, app/views/admin/products/show.html.erb
admin/products/index.html.erbのステータス表示の記述を一部修正、
show.html.erbの税込価格表示の記述を追加。
このブランチで編集したのはindexページとshowページだけになります。
（イシューのタイトルとコミットメッセージに誤りがあったのでここで訂正しておきます。）
=> Edit admin/products/index.html.erb and show.html.erb

app/controllers/products_controller.rb, app/views/products/index.html.erb, app/views/products/show.html.erb
customer/productのコントローラーとviewの編集，　priceの修正
=> #73 customer/productのコントローラーとviewの編集，　priceの修正

app/controllers/customers/registrations_controller.rb, app/views/customers/confirm_unsubscribing.html.erb
customer/unsubscribingの編集とRegistrations_Controllerへの退会処理の追加
deviseのRegistrations_Controllerのupdate action下に退会処理の機能を追加しました。
=> #75 customer/unsubscribingの編集とRegistrations_Controllerへの退会処理の追加

app/controllers/customers/registrations_controller.rb, app/controllers/shipping_addresses_controller.rb, app/views/customers/confirm_unsubscribing.html.erb, app/views/shipping_addresses/edit.html.erb, app/views/shipping_addresses/index.html.erb
shipping_addressのコントローラーとviewにスペルミスや定義できてないものがあったので修正しました。
=> #77　customer/shipping_addressesの一部修正

app/views/customers/sessions/new.html.erb
customerのログイン画面を日本語に変更、
パスワード再設定のリンクだけ表示させた。
=> customer/sessions newの作成

app/controllers/application_controller.rb, app/views/customers/registrations/new.html.erb, app/views/customers/sessions/new.html.erb, config/routes.rb
住所名と建物名を分ける方法がわからなかったのでまとめてしまいました。
また余裕のある時に調べてみようと思います。
=> #51 devise/register new controllerの作成

app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb
admin/products/viewsのnew,show,editに発生していたエラーを解消しました。
indexの方はニアミスがあってので一部修正しました。
=> #80 Edit admin/products/views, index,new,show,edit

config/routes.rb
=> #87 customer/show と customer/confim_unsubscribing のルーティングを修正

app/views/customers/registrations/new.html.erb
=> #89 customer/registration/newの修正

app/views/homes/top.html.erb
=> #91 Edit homes/top.html.erb

app/controllers/shipping_addresses_controller.rb, app/models/shipping_address.rb, app/views/customers/show.html.erb, app/views/shipping_addresses/index.html.erb
customer/shipping_addressのコントローラーとviewの修正　追加customerのshow
=> #94 customer/shipping_addressのコントローラーとviewの修正　追加customerのshow

app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb
admin/customersの index,show,edit に発生していたエラーを解消。
=> #96 Edit admin/customers/index,show,edit

app/controllers/products_controller.rb, app/views/products/show.html.erb
カスタマーのプロダクトコントローラとshowページのエラーを解消しました。
=> #98 Edit customer/product_controller and product/show.html

app/models/order.rb
=> #107 orderモデルを修正

config/application.rb
=> #109 タイムゾーンを修正

app/controllers/cart_items_controller.rb, app/controllers/orders_controller.rb, app/views/layouts/application.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb
=> #114 order, cart_item のコントローラを修正

app/views/products/index.html.erb
=> #117 customer/productのindex一部修正

app/controllers/application_controller.rb
=> #119 adminとuserとでログイン後のroutesの設定

app/controllers/admin/categories_controller.rb, app/controllers/admin/customers_controller.rb, app/controllers/admin/products_controller.rb, app/views/admin/categories/edit.html.erb, app/views/admin/categories/index.html.erb, app/views/admin/customers/edit.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb
アドミンのカテゴリー、カスタマー、プロダクトの該当箇所にエラーメッセージを追加。
=> #116 Add error message function

app/controllers/cart_items_controller.rb, app/controllers/orders_controller.rb
=> #122 cart_items コントローラーを修正

app/controllers/admin/homes_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/application_controller.rb, app/controllers/orders_controller.rb, app/models/order.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb
=> #128 order/controllerの不具合修正

app/controllers/admin/customers_controller.rb, app/controllers/admin/products_controller.rb, app/views/admin/categories/index.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/products/index.html.erb, config/initializers/kaminari_config.rb
アドミン側のカスタマー・プロダクトのページネーションを追加しました。
あとは、アドミン側のカテゴリーのindexページに一部修正を加えました。
=> #125 Add pagenate function

app/controllers/admin/orders_controller.rb, app/views/admin/orders/index.html.erb
=> #134 admin/order indexにページネーション

app/controllers/application_controller.rb, app/controllers/customers/registrations_controller.rb, app/controllers/homes_controller.rb, app/views/customers/confirm_unsubscribing.html.erb
=> #138 退会処理の修正

app/models/cart_item.rb, app/models/customer.rb, app/models/shipping_address.rb
=> modelのvalidates

config/routes.rb
=> #154 routes を修正

app/views/customers/registrations/edit.html.erb
=> #141 退会リンクの作成

app/views/layouts/application.html.erb
=> #144 adminヘッダーにログアウトリンクの作成

app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb
=> #164 Add css

app/views/customers/confirm_unsubscribing.html.erb, app/views/customers/show.html.erb
customers/customerのshowとunsubscribingのviewの編集
=> #180 customers/customerのshowとunsubscribingのviewの編集

app/views/customers/confirm_unsubscribing.html.erb, app/views/customers/show.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb
customers/productsのindex showのview編集
index ページの商品の一覧表示は書けましたが
上限を超えた場合　＜１　２　３　４＞（ページ選択）
と表示をする機能は作っていません。
=> #182　customers/productsのindex showのview編集

app/views/customers/confirm_unsubscribing.html.erb, app/views/customers/show.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb, app/views/shipping_addresses/edit.html.erb, app/views/shipping_addresses/index.html.erb
issueでshowとしましたがeditとindexを編集しました
indexで登録内容一覧table内にボタンを加えると
paddingが効かなく
デザインが崩れてしまっています。
=> #184　shipping_addressesのeditとindexの編集

app/views/admin/homes/top.html.erb
=> #146 admin/homeにbootstrapを適用

app/views/admin/orders/index.html.erb
=> #147 tableにbootstrap を適用

app/views/admin/orders/show.html.erb
=> #148 admin/order showにbootstrapを適用

app/views/customers/registrations/new.html.erb
=> #152 customer/registar new bootstrap

app/views/customers/registrations/edit.html.erb, app/views/customers/registrations/new.html.erb
=> #153 customer/registar edit bootstarap

app/controllers/application_controller.rb, app/controllers/customers/registrations_controller.rb, app/models/customer.rb
=> passwordなしでupdate可能

app/views/orders/show.html.erb
=> #193 Add css

app/views/products/show.html.erb
=> #199 Edit products/show.html.erb

app/views/orders/show.html.erb
カスタマーのorders#showのbootstrapの記述を正しいものに修正しました。
=> #203 Edit css

app/controllers/admin/categories_controller.rb, app/views/admin/categories/_index.html.erb, app/views/admin/categories/_new.html.erb, app/views/admin/categories/create.js.erb, app/views/admin/categories/edit.html.erb, app/views/admin/categories/index.html.erb
admin/categoriesのindexページに非同期通信を実装しました。
=> #233 Add Ajax
